service: mini-exchange
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_NAME: ${env:DB_NAME}
    API_SECRET: ${env:API_KEY}

functions:
  depositCrypto:
    handler: handler.deposit
    events:
      - httpApi:
          path: /deposit
          method: post
  getTransactions:
    handler: handler.getHistory
    events:
      - httpApi:
          path: /transactions/{id}
          method: get
  getBalance:
    handler: handler.getBalance
    events:
      - httpApi:
          path: /balance/{id}
          method: get
